name: Master CD Pipeline

on:
  release:
    types: [published]

jobs:
  master_publish_to_nmpjs:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true
    #needs: [release_on_merge]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        always-auth: true
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Ignore Workspace root check
      run: yarn global add npm-cli-login --ignore-workspace-root-check  

    - name: Build project
      run: yarn build

    - name: Set token
      run: echo \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > ~/.npmrc

    - name: Set package version to release version
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        for package in packages/*; do
        if [ -d "$package" ]; then
            echo "Setting version for $package to $VERSION"
            cd $package
            echo $VERSION
            npm version $VERSION --no-git-tag-version
            cd - > /dev/null
        fi
        done

    - name: Publish React SDK package
      run: |
        echo "Publishing React SDK package"
        #echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        cd packages/react
        echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        npm publish --no-workspaces     
                
    - name: Publish Javascript SDK package
      run: |
        echo "Publishing Javascript SDK package"
        #echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        cd packages/javascript-sdk
        echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        npm publish --no-workspaces  

    - name: Publish Nextjs SDK package
      run: |
        echo "Publishing Nextjs SDK package"
        #echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        cd packages/nextjs
        echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        npm publish --no-workspaces  

    - name: Publish React SDK package
      run: |
        echo "Publishing React SDK package"
        #echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        cd packages/react
        echo  \"//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}\" > .npmrc"
        npm publish --no-workspaces          